# Generated by Django 2.2.6 on 2019-10-29 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('cource_abbreviation', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cource_name', models.CharField(default=None, max_length=30)),
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(default=None, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=30, unique=True)),
                ('n_credit', models.IntegerField(default=2)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.Category')),
                ('cource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.Cource')),
            ],
            options={
                'verbose_name': '授業科目',
                'verbose_name_plural': '授業科目',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ステータス',
                'verbose_name_plural': 'ステータス',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
