# Generated by Django 2.2.6 on 2019-10-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='n_credit',
            new_name='credits',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cource',
            name='cource_abbreviation',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cource',
            name='cource_name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
