# Generated by Django 2.2.6 on 2019-10-29 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0002_auto_20191029_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.Cource')),
            ],
            options={
                'verbose_name': '所属コース',
                'verbose_name_plural': '所属コース',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doing', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ステータス',
                'verbose_name_plural': 'ステータス',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cource',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='status',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Subject'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cource_subject',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('user', 'subject')},
        ),
    ]
