# Generated by Django 2.2.6 on 2019-10-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20191029_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cource_subject',
            options={'verbose_name': '科目のコース', 'verbose_name_plural': '科目のコース'},
        ),
        migrations.RenameField(
            model_name='cource_subject',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
